Repository stableway/anmeldung-berlin, pull requests merged in 2023-12, with the labels that each got.

#6 Email confirmation was not filled out by the script
  index.js
Labels: bug

#8 Playwright. MailSlurp Email Verification.
  .gitignore
  Dockerfile
  LICENSE
  README.md
  config.json
  constants.json
  index.js
  package-lock.json
  package.json
  playwright.config.js
  tests/appointment.test.js
Labels: documentation, enhancement, dependencies

#9 Fix README step-by-step & output instructions
  README.md
Labels: bug, documentation

#10 Fix default values in config.json
  config.json
Labels: bug

#12 Fix typo in env var
  README.md
Labels: bug, documentation
